version: '3.8'

services:
  # Serwer Ollama z lokalnym LLM - zoptymalizowany
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11435}:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - MODEL=${OLLAMA_MODEL:-mistral}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 6G  # Ogranicz pamięć, aby uniknąć przeładowania
        reservations:
          memory: 1G  # Zarezerwuj minimum pamięci dla kontenera

  # Testowy serwer email (MailHog)
  mailserver:
    image: mailhog/mailhog:latest
    container_name: mailserver
    ports:
      - "${MAILHOG_SMTP_PORT:-1026}:1025"
      - "${MAILHOG_UI_PORT:-8026}:8025"
    networks:
      - app-network
    restart: unless-stopped
    # Na produkcji zastąpić rzeczywistym serwerem

  # Node-RED do integracji
  nodered:
    image: nodered/node-red:latest
    container_name: nodered-email-llm
    user: "1000:1000"
    ports:
      - "${NODERED_PORT:-1880}:1880"
    volumes:
      - ./data/node-red:/data
      - ./data/sqlite:/data/sqlite
    environment:
      - TZ=Europe/Warsaw
      - NODE_RED_ENABLE_PROJECTS=false
      - NODE_RED_ENABLE_SAFE_MODE=false
      - NODE_OPTIONS=--max_old_space_size=512
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_IMAP_HOST=${EMAIL_IMAP_HOST}
      - EMAIL_IMAP_PORT=${EMAIL_IMAP_PORT}
      - EMAIL_IMAP_FOLDER=${EMAIL_IMAP_FOLDER}
      - NODERED_USERNAME=${NODERED_USERNAME}
      - NODERED_PASSWORD=${NODERED_PASSWORD}
    depends_on:
      - ollama
      - mailserver
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Narzędzie administracyjne dla bazy SQLite
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    environment:
      - ADMINER_DEFAULT_DRIVER=sqlite
    volumes:
      - ./data/sqlite:/data:ro
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_models:
  
networks:
  app-network:
    driver: bridge