version: '3.8'

services:
  # Serwer Ollama z lokalnym LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11435}:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - MODEL=${OLLAMA_MODEL:-phi3:mini}  # Używamy lekkiego modelu dla szybszego startu
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    entrypoint: >
      sh -c "ollama serve &
             sleep 10 &&
             if ! ollama list | grep -q $${MODEL}; then
               echo 'Pobieranie modelu '$${MODEL}
               ollama pull $${MODEL}
             fi &&
             wait"

  # Testowy serwer email (MailHog)
  mailserver:
    image: mailhog/mailhog:latest
    container_name: mailserver
    ports:
      - "${MAILHOG_SMTP_PORT:-1026}:1025"
      - "${MAILHOG_UI_PORT:-8026}:8025"
    networks:
      - app-network
    restart: unless-stopped

  # Node-RED do integracji - zbudowany z preinstalowanymi modułami
  nodered:
    build:
      context: ./node-red-custom
      dockerfile: Dockerfile
    container_name: nodered-email-llm
    ports:
      - "${NODERED_PORT:-1880}:1880"
    volumes:
      - ./data/node-red:/data
      - ./data/sqlite:/data/sqlite
    environment:
      - TZ=Europe/Warsaw
      - NODE_RED_ENABLE_PROJECTS=false
      - NODE_RED_ENABLE_SAFE_MODE=false
      - NODE_OPTIONS=--max_old_space_size=512
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-phi3:mini}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH:-/data/sqlite/emails.db}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_IMAP_HOST=${EMAIL_IMAP_HOST}
      - EMAIL_IMAP_PORT=${EMAIL_IMAP_PORT}
      - EMAIL_IMAP_FOLDER=${EMAIL_IMAP_FOLDER}
      - NODERED_USERNAME=${NODERED_USERNAME}
      - NODERED_PASSWORD=${NODERED_PASSWORD}
    depends_on:
      - ollama
      - mailserver
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Narzędzie administracyjne dla bazy SQLite
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    environment:
      - ADMINER_DEFAULT_DRIVER=sqlite
    volumes:
      - ./data/sqlite:/data:ro
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_models:
  
networks:
  app-network:
    driver: bridge